---
- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
  tags: vars

- name: Ensure the VM volumes do not exist
  script: >
    destroy_virt_volume.sh
    {{ item.name }}
    {{ item.pool }}
  with_items: "{{ volumes }}"
  register: volume_result
  environment: "{{ libvirt_vm_volume_creation_env }}"
  changed_when:
    - volume_result is success
    - (volume_result.stdout | from_json).changed | default(True)
  become: yes
